apiVersion: batch/v1
kind: CronJob
metadata:
  name: model-autoscaler
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scaler
              image: scaler:latest
              imagePullPolicy: Never
          restartPolicy: OnFailure
