apiVersion: batch/v1
kind: CronJob
metadata:
  name: model-autoscaler
spec:
  schedule: "*/5 * * * *" # every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scaler
              image: <your-dockerhub-username>/scaler:latest
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
