apiVersion: batch/v1
kind: CronJob
metadata:
  name: scaler-cronjob
spec:
  schedule: "0 */4 * * *" # */5 * * * * Runs every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: scaler-sa
          containers:
            - name: scaler
              image: solankiom/scaler:latest
              imagePullPolicy: Always
          restartPolicy: OnFailure
