apiVersion: v1
kind: ServiceAccount
metadata:
  name: scaler-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scaler-role
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scaler-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scaler-role
subjects:
  - kind: ServiceAccount
    name: scaler-sa
